// build-cities.mjs
// Runs automatically during deploy (see the GitHub Actions workflow).
// It downloads the free GeoNames city database (cities15000.zip —
// every city in the world with population 15,000+, about 31,000 cities),
// and writes a compact version into cities-data.js so the Worker can
// look up birth-city coordinates without calling any outside service.
//
// GeoNames data is free under the Creative Commons Attribution 4.0
// license (https://www.geonames.org/). Attribution note: city data
// from GeoNames.org.
//
// If the automatic download fails (network hiccup etc.), the built-in
// city list in cities.js still keeps the site working.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { inflateRawSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = join(HERE, "cities-data.js");
const ZIP_URL = "https://download.geonames.org/export/dump/cities15000.zip";
const LOCAL_TXT = join(HERE, "cities15000.txt");

function extractFromZip(buf) {
  // Locate End Of Central Directory record (signature 0x06054b50)
  let eocd = -1;
  for (let i = buf.length - 22; i >= Math.max(0, buf.length - 65558); i--) {
    if (buf.readUInt32LE(i) === 0x06054b50) { eocd = i; break; }
  }
  if (eocd < 0) throw new Error("Not a valid zip file (no end-of-central-directory).");
  const cdOffset = buf.readUInt32LE(eocd + 16);

  // First central directory entry (signature 0x02014b50)
  if (buf.readUInt32LE(cdOffset) !== 0x02014b50) throw new Error("Bad central directory.");
  const method = buf.readUInt16LE(cdOffset + 10);
  const compSize = buf.readUInt32LE(cdOffset + 20);
  const localOffset = buf.readUInt32LE(cdOffset + 42);

  // Local file header (signature 0x04034b50)
  if (buf.readUInt32LE(localOffset) !== 0x04034b50) throw new Error("Bad local file header.");
  const nameLen = buf.readUInt16LE(localOffset + 26);
  const extraLen = buf.readUInt16LE(localOffset + 28);
  const dataStart = localOffset + 30 + nameLen + extraLen;
  const data = buf.subarray(dataStart, dataStart + compSize);

  if (method === 0) return data;                 // stored
  if (method === 8) return inflateRawSync(data); // deflated
  throw new Error(`Unsupported zip compression method: ${method}`);
}

async function getText() {
  if (existsSync(LOCAL_TXT)) {
    console.log("Using local cities15000.txt");
    return readFileSync(LOCAL_TXT, "utf8");
  }
  console.log("Downloading city database from GeoNames (about 3 MB)...");
  const res = await fetch(ZIP_URL);
  if (!res.ok) throw new Error(`Download failed: HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  console.log("Unpacking...");
  return extractFromZip(buf).toString("utf8");
}

function clean(s) {
  return (s || "").replaceAll("|", "/").trim();
}

let text;
try {
  text = await getText();
} catch (err) {
  // Never break the site deploy over a download hiccup — the built-in
  // major-cities list keeps things working until the next successful build.
  console.warn("City database download failed:", err.message);
  console.warn("Deploy continues with the built-in city list.");
  process.exit(0);
}
const lines = text.split("\n");
const out = [];
for (const line of lines) {
  if (!line.trim()) continue;
  const c = line.split("\t");
  // GeoNames columns: 1=name 2=asciiname 4=lat 5=lng 8=countryCode 10=admin1 14=population
  const name = clean(c[1]);
  const ascii = clean(c[2]);
  const lat = parseFloat(c[4]);
  const lng = parseFloat(c[5]);
  const cc = clean(c[8]).toUpperCase();
  const admin1 = clean(c[10]);
  const pop = parseInt(c[14], 10) || 0;
  if (!name || !cc || Number.isNaN(lat) || Number.isNaN(lng)) continue;
  out.push(
    `${name}|${ascii}|${cc}|${admin1}|${lat.toFixed(4)}|${lng.toFixed(4)}|${pop}`
  );
}

const js =
  `// cities-data.js\n` +
  `// GENERATED by build-cities.mjs on ${new Date().toISOString().slice(0, 10)}\n` +
  `// City data from GeoNames.org (CC BY 4.0). ${out.length} cities.\n` +
  `// Do not edit by hand — re-run the script to refresh.\n\n` +
  `export const CITIES_DATA = ${JSON.stringify(out.join("\n"))};\n`;

writeFileSync(OUT_FILE, js);
console.log(`Done! Wrote ${out.length} cities to cities-data.js`);
console.log("Now deploy the Worker again and worldwide city lookup is live.");
