// cities.js
// Turns a birth city + country into coordinates without calling any
// external service. Two layers:
//
//   1. cities-data.js — the full worldwide dataset (~31,000 cities).
//      Generated by running build-cities.mjs (Cloudflare's build step).
//      If it hasn't run yet, this layer is simply empty and layer 2 is used.
//
//   2. A built-in list of major world cities, so the site works even
//      before the full dataset is generated.
//
// If neither layer matches, we fall back to New York — which is
// exactly what the old code did when a city couldn't be resolved.

import { CITIES_DATA } from "./cities-data.js";

// ---------------------------------------------------------------
// Layer 2: built-in major cities.  [name, country, admin1, lat, lng]
// admin1 is the US state / region code where useful, "" otherwise.
// ---------------------------------------------------------------
const MAJOR_CITIES = [
  ["new york", "US", "NY", 40.71, -74.01],
  ["los angeles", "US", "CA", 34.05, -118.24],
  ["chicago", "US", "IL", 41.88, -87.63],
  ["houston", "US", "TX", 29.76, -95.37],
  ["phoenix", "US", "AZ", 33.45, -112.07],
  ["philadelphia", "US", "PA", 39.95, -75.17],
  ["san antonio", "US", "TX", 29.42, -98.49],
  ["san diego", "US", "CA", 32.72, -117.16],
  ["dallas", "US", "TX", 32.78, -96.80],
  ["austin", "US", "TX", 30.27, -97.74],
  ["jacksonville", "US", "FL", 30.33, -81.66],
  ["san jose", "US", "CA", 37.34, -121.89],
  ["fort worth", "US", "TX", 32.75, -97.33],
  ["columbus", "US", "OH", 39.96, -83.00],
  ["charlotte", "US", "NC", 35.23, -80.84],
  ["indianapolis", "US", "IN", 39.77, -86.16],
  ["san francisco", "US", "CA", 37.77, -122.42],
  ["seattle", "US", "WA", 47.61, -122.33],
  ["denver", "US", "CO", 39.74, -104.99],
  ["washington", "US", "DC", 38.90, -77.04],
  ["boston", "US", "MA", 42.36, -71.06],
  ["el paso", "US", "TX", 31.76, -106.49],
  ["nashville", "US", "TN", 36.16, -86.78],
  ["detroit", "US", "MI", 42.33, -83.05],
  ["oklahoma city", "US", "OK", 35.47, -97.52],
  ["portland", "US", "OR", 45.52, -122.68],
  ["las vegas", "US", "NV", 36.17, -115.14],
  ["memphis", "US", "TN", 35.15, -90.05],
  ["louisville", "US", "KY", 38.25, -85.76],
  ["baltimore", "US", "MD", 39.29, -76.61],
  ["milwaukee", "US", "WI", 43.04, -87.91],
  ["albuquerque", "US", "NM", 35.08, -106.65],
  ["tucson", "US", "AZ", 32.22, -110.97],
  ["fresno", "US", "CA", 36.75, -119.77],
  ["sacramento", "US", "CA", 38.58, -121.49],
  ["kansas city", "US", "MO", 39.10, -94.58],
  ["mesa", "US", "AZ", 33.42, -111.83],
  ["atlanta", "US", "GA", 33.75, -84.39],
  ["omaha", "US", "NE", 41.26, -95.94],
  ["colorado springs", "US", "CO", 38.83, -104.82],
  ["raleigh", "US", "NC", 35.78, -78.64],
  ["miami", "US", "FL", 25.76, -80.19],
  ["virginia beach", "US", "VA", 36.85, -75.98],
  ["oakland", "US", "CA", 37.80, -122.27],
  ["minneapolis", "US", "MN", 44.98, -93.27],
  ["tulsa", "US", "OK", 36.15, -95.99],
  ["tampa", "US", "FL", 27.95, -82.46],
  ["orlando", "US", "FL", 28.54, -81.38],
  ["new orleans", "US", "LA", 29.95, -90.07],
  ["cleveland", "US", "OH", 41.50, -81.69],
  ["pittsburgh", "US", "PA", 40.44, -79.99],
  ["cincinnati", "US", "OH", 39.10, -84.51],
  ["st louis", "US", "MO", 38.63, -90.20],
  ["saint louis", "US", "MO", 38.63, -90.20],
  ["salt lake city", "US", "UT", 40.76, -111.89],
  ["honolulu", "US", "HI", 21.31, -157.86],
  ["anchorage", "US", "AK", 61.22, -149.90],
  ["buffalo", "US", "NY", 42.89, -78.88],
  ["richmond", "US", "VA", 37.54, -77.44],
  ["birmingham", "US", "AL", 33.52, -86.80],
  ["grand rapids", "US", "MI", 42.96, -85.67],
  ["boise", "US", "ID", 43.62, -116.20],
  ["des moines", "US", "IA", 41.59, -93.62],
  ["little rock", "US", "AR", 34.75, -92.29],
  ["jackson", "US", "MS", 32.30, -90.18],
  ["charleston", "US", "SC", 32.78, -79.93],
  ["savannah", "US", "GA", 32.08, -81.09],
  ["toronto", "CA", "", 43.65, -79.38],
  ["montreal", "CA", "", 45.50, -73.57],
  ["vancouver", "CA", "", 49.28, -123.12],
  ["calgary", "CA", "", 51.05, -114.07],
  ["ottawa", "CA", "", 45.42, -75.70],
  ["edmonton", "CA", "", 53.55, -113.49],
  ["winnipeg", "CA", "", 49.90, -97.14],
  ["mexico city", "MX", "", 19.43, -99.13],
  ["guadalajara", "MX", "", 20.66, -103.35],
  ["monterrey", "MX", "", 25.67, -100.31],
  ["london", "GB", "", 51.51, -0.13],
  ["manchester", "GB", "", 53.48, -2.24],
  ["birmingham", "GB", "", 52.48, -1.90],
  ["glasgow", "GB", "", 55.86, -4.25],
  ["edinburgh", "GB", "", 55.95, -3.19],
  ["liverpool", "GB", "", 53.41, -2.98],
  ["dublin", "IE", "", 53.35, -6.26],
  ["paris", "FR", "", 48.86, 2.35],
  ["marseille", "FR", "", 43.30, 5.37],
  ["lyon", "FR", "", 45.76, 4.84],
  ["berlin", "DE", "", 52.52, 13.40],
  ["hamburg", "DE", "", 53.55, 9.99],
  ["munich", "DE", "", 48.14, 11.58],
  ["frankfurt", "DE", "", 50.11, 8.68],
  ["madrid", "ES", "", 40.42, -3.70],
  ["barcelona", "ES", "", 41.39, 2.17],
  ["lisbon", "PT", "", 38.72, -9.14],
  ["rome", "IT", "", 41.89, 12.48],
  ["milan", "IT", "", 45.46, 9.19],
  ["naples", "IT", "", 40.85, 14.27],
  ["amsterdam", "NL", "", 52.37, 4.90],
  ["brussels", "BE", "", 50.85, 4.35],
  ["zurich", "CH", "", 47.37, 8.54],
  ["geneva", "CH", "", 46.20, 6.14],
  ["vienna", "AT", "", 48.21, 16.37],
  ["stockholm", "SE", "", 59.33, 18.06],
  ["oslo", "NO", "", 59.91, 10.75],
  ["copenhagen", "DK", "", 55.68, 12.57],
  ["helsinki", "FI", "", 60.17, 24.94],
  ["warsaw", "PL", "", 52.23, 21.01],
  ["moscow", "RU", "", 55.76, 37.62],
  ["kyiv", "UA", "", 50.45, 30.52],
  ["kiev", "UA", "", 50.45, 30.52],
  ["athens", "GR", "", 37.98, 23.73],
  ["istanbul", "TR", "", 41.01, 28.98],
  ["ankara", "TR", "", 39.93, 32.86],
  ["tel aviv", "IL", "", 32.09, 34.78],
  ["jerusalem", "IL", "", 31.77, 35.21],
  ["riyadh", "SA", "", 24.71, 46.68],
  ["dubai", "AE", "", 25.20, 55.27],
  ["abu dhabi", "AE", "", 24.45, 54.38],
  ["cairo", "EG", "", 30.04, 31.24],
  ["lagos", "NG", "", 6.52, 3.38],
  ["nairobi", "KE", "", -1.29, 36.82],
  ["accra", "GH", "", 5.56, -0.20],
  ["johannesburg", "ZA", "", -26.20, 28.05],
  ["cape town", "ZA", "", -33.92, 18.42],
  ["casablanca", "MA", "", 33.57, -7.59],
  ["mumbai", "IN", "", 19.08, 72.88],
  ["delhi", "IN", "", 28.61, 77.21],
  ["new delhi", "IN", "", 28.61, 77.21],
  ["bangalore", "IN", "", 12.97, 77.59],
  ["kolkata", "IN", "", 22.57, 88.36],
  ["chennai", "IN", "", 13.08, 80.27],
  ["hyderabad", "IN", "", 17.39, 78.49],
  ["karachi", "PK", "", 24.86, 67.01],
  ["lahore", "PK", "", 31.55, 74.34],
  ["islamabad", "PK", "", 33.69, 73.06],
  ["dhaka", "BD", "", 23.81, 90.41],
  ["colombo", "LK", "", 6.93, 79.85],
  ["kathmandu", "NP", "", 27.72, 85.32],
  ["beijing", "CN", "", 39.90, 116.41],
  ["shanghai", "CN", "", 31.23, 121.47],
  ["hong kong", "HK", "", 22.32, 114.17],
  ["taipei", "TW", "", 25.03, 121.57],
  ["tokyo", "JP", "", 35.68, 139.69],
  ["osaka", "JP", "", 34.69, 135.50],
  ["seoul", "KR", "", 37.57, 126.98],
  ["bangkok", "TH", "", 13.76, 100.50],
  ["hanoi", "VN", "", 21.03, 105.85],
  ["ho chi minh city", "VN", "", 10.82, 106.63],
  ["saigon", "VN", "", 10.82, 106.63],
  ["jakarta", "ID", "", -6.21, 106.85],
  ["manila", "PH", "", 14.60, 120.98],
  ["kuala lumpur", "MY", "", 3.14, 101.69],
  ["singapore", "SG", "", 1.35, 103.82],
  ["sydney", "AU", "", -33.87, 151.21],
  ["melbourne", "AU", "", -37.81, 144.96],
  ["brisbane", "AU", "", -27.47, 153.03],
  ["perth", "AU", "", -31.95, 115.86],
  ["adelaide", "AU", "", -34.93, 138.60],
  ["auckland", "NZ", "", -36.85, 174.76],
  ["wellington", "NZ", "", -41.29, 174.78],
  ["sao paulo", "BR", "", -23.55, -46.63],
  ["rio de janeiro", "BR", "", -22.91, -43.17],
  ["buenos aires", "AR", "", -34.60, -58.38],
  ["bogota", "CO", "", 4.71, -74.07],
  ["santiago", "CL", "", -33.45, -70.67],
  ["lima", "PE", "", -12.05, -77.04],
  ["havana", "CU", "", 23.11, -82.37],
  ["kingston", "JM", "", 17.97, -76.79],
  ["santo domingo", "DO", "", 18.49, -69.93],
];

// ---------------------------------------------------------------
// Parse the generated dataset (lazy, once per Worker instance).
// Format per line: name|asciiName|countryCode|admin1|lat|lng|population
// ---------------------------------------------------------------
let datasetIndex = null;

function buildDatasetIndex() {
  const index = new Map(); // "name|CC" -> array of entries
  if (!CITIES_DATA || CITIES_DATA.length === 0) return index;
  for (const line of CITIES_DATA.split("\n")) {
    if (!line) continue;
    const parts = line.split("|");
    if (parts.length < 7) continue;
    const [name, ascii, cc, admin1, latS, lngS, popS] = parts;
    const entry = {
      name,
      country: cc,
      admin1,
      lat: parseFloat(latS),
      lng: parseFloat(lngS),
      pop: parseInt(popS, 10) || 0,
    };
    for (const key of new Set([
      `${name.toLowerCase()}|${cc}`,
      `${ascii.toLowerCase()}|${cc}`,
    ])) {
      if (!index.has(key)) index.set(key, []);
      index.get(key).push(entry);
    }
  }
  return index;
}

function normState(state) {
  return (state || "").trim().toLowerCase();
}

/**
 * Find coordinates for a city.
 * @param {string} cityName
 * @param {string} countryCode ISO-2 (e.g. "US")
 * @param {string} [state] optional state/province, used to break ties
 * @returns {{name, country, lat, lng, source} | null}
 */
export function findCity(cityName, countryCode, state) {
  const q = (cityName || "").trim().toLowerCase();
  const cc = (countryCode || "US").toUpperCase();
  const st = normState(state);
  if (!q) return fallbackNewYork();

  // Layer 1: full dataset
  if (datasetIndex === null) datasetIndex = buildDatasetIndex();
  const hits = datasetIndex.get(`${q}|${cc}`);
  if (hits && hits.length > 0) {
    let pick = hits;
    if (st) {
      const stateHits = hits.filter(
        (h) => h.admin1 && (h.admin1.toLowerCase() === st || h.admin1.toLowerCase().startsWith(st))
      );
      if (stateHits.length > 0) pick = stateHits;
    }
    const best = pick.reduce((a, b) => (b.pop > a.pop ? b : a));
    return { name: best.name, country: best.country, lat: best.lat, lng: best.lng, source: "dataset" };
  }

  // Layer 2: built-in major cities
  let candidates = MAJOR_CITIES.filter(([n, c]) => n === q && c === cc);
  if (candidates.length === 0) {
    candidates = MAJOR_CITIES.filter(([n]) => n === q); // any country
  }
  if (candidates.length > 0) {
    let pick = candidates[0];
    if (st) {
      const stMatch = candidates.find(([, , a1]) => a1 && a1.toLowerCase() === st);
      if (stMatch) pick = stMatch;
    }
    return { name: pick[0], country: pick[1], lat: pick[3], lng: pick[4], source: "fallback" };
  }

  // Layer 3: same last-resort behavior as the old code
  return fallbackNewYork();
}

function fallbackNewYork() {
  return { name: "new york", country: "US", lat: 40.71, lng: -74.01, source: "fallback-default" };
}
