// Real, sourced Human Design gate content -- name, Center, and mechanism
// (gift and shadow) for all 64 gates. Same data as index.html's GATES
// object, kept in its own module so worker.js can import it without a
// bundler: astrology gets full sign/house/aspect detail in the report
// prompt, numerology gets full number+age-range detail, but gates were
// only ever sent as bare numbers, leaving the model to interpret all 64
// from memory alone with zero real grounding. This file exists so the
// report prompt can give gates the same real-data treatment.
export const GATES = {
  1:`Self-Expression. In the G Center, the identity/direction hub of the chart. This is the pressure to create something that is recognizably yours — not copied, not shaped to fit what an audience already likes. Work made from genuine impulse carries a distinct, personal signature; work built instead around anticipated approval can be technically accomplished and still read as hollow, even to the person who made it.`,
  2:`The Driver. In the G Center. This gate holds a felt sense of the right direction to move in for yourself — strong enough that other people notice it and start asking you for direction too. It isn't a conclusion reached by reasoning it out in advance; it functions more like a compass that only gives an accurate reading once you're actually in motion, which means real clarity here tends to arrive mid-action rather than before it.`,
  3:`Ordering. In the Sacral Center. This is the gate of a genuinely new beginning, and new beginnings are messy before they're workable — its function is finding real, usable order inside that mess, not skipping past it. A stretch of visible confusion right after starting something is this gate's actual working process, not a sign anything went wrong; order that looks settled before that sorting has actually happened tends to be appearance rather than the real thing.`,
  4:`Answers. In the Ajna Center. This gate produces logical answers and formulas quickly, often before all the facts are confirmed — it's built for generating a workable hypothesis, not for delivering a guaranteed conclusion. The answers it produces are often useful precisely because they arrive fast; the same speed means they can carry a confident tone whether the underlying facts are actually settled or still just a guess.`,
  5:`Fixed Rhythms. In the Sacral Center. This gate needs a consistent, personal rhythm — sleep, work, routine — and genuinely destabilizes when that rhythm gets interrupted by someone else's schedule or demands. That's not rigidity for its own sake: disrupted rhythm here has a real, measurable cost in energy and follow-through, the same way a machine tuned to run at one speed loses efficiency at another.`,
  6:`Friction. In the Solar Plexus Center. This gate governs emotional intimacy, and real intimacy here runs through friction first — tension, disagreement, or conflict that has to move through before closeness becomes possible, not instead of it. A connection that stays smooth and conflict-free with this gate active tends to also stay at the surface; the depth and the friction are part of the same mechanism, not opposites to choose between.`,
  7:`The Role. In the G Center. This is quiet, style-based leadership — leading through how you occupy a position, not by giving orders. People often follow because of the way you carry a role, not because you asked them to, and that same leadership can also arrive before anyone was actually looking to you for it, read by others as presumption even though it feels like natural authority from the inside.`,
  8:`Contribution. In the Throat Center. This gate expresses individuality out loud — a personal example or a distinct way of doing things that can end up giving a group real direction, without any title attached to it. The same contribution reads very differently depending on where it comes from: offered as simply being yourself in front of others, it draws people in; offered as a performance aimed at being noticed, it tends to read as exactly that, even when the content is identical.`,
  9:`Focus. In the Sacral Center. This gate has real staying power for small, precise details that other people skip past — the follow-through that turns a plan into something that actually works. That same narrowing of attention can also mean losing sight of the larger point of the work while deep inside one of its details.`,
  10:`Behavior of the Self. In the G Center. This gate is about behaving as yourself, in your own way, regardless of who's watching — a kind of self-regard expressed through conduct rather than through any claim about it. The same gate can also start adapting its behavior to whoever's in the room and what will be approved of there, a different and more fragile version of the same instinct.`,
  11:`Ideas. In the Ajna Center. This gate generates concepts, one after another, and finds real satisfaction in sharing them — teaching, discussing, putting an idea into circulation rather than acting on it directly. Not every idea produced here is meant to be built; some exist to be talked through and let go of, and treating each one as something that must be executed tends to scatter energy across many half-started things instead.`,
  12:`Caution. In the Throat Center. This gate can articulate something genuinely moving, but it's mood-dependent — it needs the right social moment to land, and the same words said at the wrong moment can fall flat or get misread. The instinct to stay quiet until the moment feels right is closer to accurate timing sense than to shyness, and speaking on impulse instead, ahead of that sense, is usually what produces the awkward result this gate is known for.`,
  13:`The Listener. In the G Center. This gate draws people in to tell their real stories and secrets — you end up as the person others confide in, sometimes without meaning to invite it. Held one way, that's real fellowship: a genuine record of what people have actually lived through. Held another way, the same gate turns into gossip or grievance carried long after it was first told, the difference being what happens to what's heard once it's been received.`,
  14:`Power Skills. In the Sacral Center. This gate is real competence at generating resources — money, assets, momentum — through sustained, skilled effort, not luck. That same energy is strong enough that it can also become about power and possession for their own sake, detached from whatever the resources were originally being built toward.`,
  15:`Extremes. In the G Center. This gate holds space for the full range of human behavior — including people whose rhythms or extremes look nothing like your own — and functions by including that range rather than judging it. The same gate carries its own extremes too, swinging between bursts of high activity and stretches of near-total inertia, alongside a real, unforced acceptance of people exactly as they are.`,
  16:`Skills. In the Throat Center. This gate is enthusiasm plus repetition — real skill built by practicing something enough times that it becomes natural talent, then performed with visible confidence. Enthusiasm alone isn't the same as mastery here; performed before the repetition has actually happened, the same confidence can outrun the skill behind it.`,
  17:`Opinion. In the Ajna Center. This gate forms clear, logical opinions about how things should go, based on real patterns it's noticed — and it wants those opinions followed, since from its own vantage they're sound. The opinions are frequently accurate, and they're still one person's read of a pattern rather than settled fact, held with a certainty that doesn't always leave visible room for being revised.`,
  18:`Correction. In the Spleen Center. This gate has a sharp instinct for spotting what's flawed or broken and a real drive to fix it — genuinely useful aimed at systems, processes, or work that needs improving. The same instinct aimed at a person instead of a system reads as criticism or judgment, even though it comes from the identical impulse to fix something broken.`,
  19:`Wanting. In the Root Center. This gate is finely tuned to what's needed for real support and belonging — sensing when someone, including yourself, is under-resourced before it becomes an obvious problem, a genuine early-warning system for unmet needs. That sensitivity runs in both directions: it can mean tending to everyone else's version of that need while your own goes unnamed, or reading a need into a situation where there wasn't actually one.`,
  20:`The Now. In the Throat Center. This gate acts from whatever is true right in this moment — not from a plan made earlier, and not from overthinking what's about to happen. Its strength is genuine presence, showing up fully for what's actually in front of it; the same immediacy also means "the now" and "the first impulse" aren't always the same thing, even though acting on one can look exactly like acting on the other.`,
  21:`Control. In the Heart/Ego Center. This gate wants real, direct control over its own domain — its resources, its territory, its say in how things get run — and is willing to assert that control rather than defer it to someone else. Held over what's actually its own, that's healthy self-management; the same instinct can also reach past its own domain into controlling things, or people, that were never actually its to manage.`,
  22:`Openness. In the Solar Plexus Center. This gate carries real emotional grace — social openness and warmth that lands well specifically when the emotional timing is right. The same openness offered at the wrong emotional moment can come across as too much, or oddly timed, without the warmth itself having changed at all.`,
  23:`Assimilation. In the Throat Center. This gate takes a complex or unusual individual insight and simplifies it enough that other people can actually absorb it — genuine translation work. Delivered abruptly or at the wrong moment, the same insight can fracture a conversation instead of clarifying it, since how well this gate's translation lands depends as much on timing as on the words themselves.`,
  24:`Rationalization. In the Ajna Center. This gate keeps returning to the same thought or realization, turning it over again until it's genuinely clear — repetition in service of clarity, not being stuck. Each pass can sharpen the idea further, or it can produce the same conclusion again with more self-justification layered onto it, and the two can feel identical from the inside.`,
  25:`Innocence. In the G Center. This gate loves without attaching to a specific outcome — a kind of universal, unconditional regard that doesn't require anything back. It's genuinely rare, and it often reads as resilience: setbacks don't permanently sour this gate's basic openness to people and to life. That same openness carries real vulnerability too — it can mean taking on hurt that a more guarded approach would have avoided.`,
  26:`The Trickster. In the Heart/Ego Center. This gate is a genuine skill at persuasion and salesmanship — presenting something, including yourself, in its best, most convincing light. The same skill can also tip into shading the truth: leaving out an inconvenient detail, or remembering events selectively when it serves winning an argument.`,
  27:`Caring. In the Sacral Center. This gate carries real responsibility for other people's, and your own, wellbeing — nourishing, feeding, looking after, in a literal and practical sense as well as an emotional one. The same instinct can also run one-directional, giving care outward constantly while its own needs go untended by anyone, including the person providing the care.`,
  28:`The Game Player. In the Spleen Center. This gate is willing to risk something real in search of a life that actually feels meaningful — it would rather gamble on a purpose worth pursuing than play it safe toward nothing in particular. Risk taken for a real, considered purpose and risk taken for its own thrill can look identical in the moment, and only one of them tends to leave this gate with something to show for it afterward.`,
  29:`Perseverance. In the Sacral Center. This gate says yes to real commitments and then follows all the way through, including the hard, unglamorous middle stretch most people quit during. The yes itself can come fast, sometimes before there's been time to actually check whether the commitment is one worth that full follow-through.`,
  30:`Feelings. In the Solar Plexus Center. This gate wants to feel the full range of emotional experience — desire, longing, intensity — and treats that wanting itself as valid information rather than something to suppress. It runs hottest around wanting things it doesn't yet have, which can tip into a restless craving that getting the thing doesn't actually satisfy.`,
  31:`Influence. In the Throat Center. This gate leads through being genuinely heard and recognized by a group — real influence earned by speaking in a way others actually choose to follow, not influence claimed by title. It only functions with real followers behind it; offered before that recognition exists, the same leadership doesn't land the way it does once it's actually been given.`,
  32:`Continuity. In the Spleen Center. This gate has a real, felt instinct for what will hold up over time versus what won't — a kind of survival-level pattern recognition applied to ventures, plans, and relationships. That instinct comes bundled with a fear of failure that can make it hesitant to commit to anything until the outcome already feels certain.`,
  33:`Privacy. In the Throat Center. This gate needs real retreat — time alone to process and remember what's already happened before it can speak about it usefully. What eventually gets said, once that private processing is done, often carries real, hard-won insight that the same words wouldn't have carried if spoken before the processing was finished.`,
  34:`Power. In the Sacral Center. This gate is raw, undirected physical power — strength and capacity to act that doesn't come with its own built-in direction. Without something real to respond to, that strength can barrel through situations it wasn't actually needed for; paired with a genuine response, the same strength becomes effective, purposeful momentum.`,
  35:`Change. In the Throat Center. This gate gets restless without new experience and pushes toward change and variety almost for its own sake — not as a means to some other end. That restlessness swings between real highs when something's new and flat boredom once the novelty wears off, a cycle that repeats rather than resolves.`,
  36:`Crisis. In the Solar Plexus Center. This gate seeks new emotional territory, and getting there often runs through real turbulence or crisis first — not because life is against it, but because unfamiliar emotional ground rarely arrives smoothly. The crisis isn't a failure of this gate; it's frequently the actual mechanism by which it reaches a genuinely new emotional experience.`,
  37:`Friendship. In the Solar Plexus Center. This gate builds bonds through mutual agreements, loyalty, and warmth — the glue that holds a family or close community together in practice, not just in feeling. It runs on reciprocity: the bond needs both people actually upholding their side of it, spoken or not, and when one side stops, this gate tends to feel the shift directly, often before either person has named what changed.`,
  38:`The Fighter. In the Root Center. This gate is willing to oppose, resist, or fight for something it considers genuinely worth the fight — a real stubbornness in service of finding a purpose worth that much resistance. Directed at something trivial, the same stubbornness looks combative without an obvious reason attached to it.`,
  39:`Provocation. In the Root Center. This gate provokes — sometimes deliberately, sometimes just by its presence — in a way that tends to surface what other people actually feel underneath a polite surface, genuinely useful for cutting through evasiveness. The same provocation, without an honest question underneath it, can also read as needling people for no clear reason.`,
  40:`Aloneness. In the Heart/Ego Center. This gate takes on real responsibility for providing for others, and afterward it genuinely needs solitary rest to recover — not an indulgence, but the actual mechanism that lets it keep providing at all. Skipping that recovery to keep giving without pause tends to build resentment toward the very people being provided for, even when the giving itself was freely chosen.`,
  41:`Contraction. In the Root Center. This gate is the first, quiet stirring of a new desire or a new experience someone wants to have — a private fantasy or wish that hasn't been acted on yet. It's the seed stage, not the execution stage, and it can feel like restlessness for something not yet defined, well before the actual desire underneath it has a name.`,
  42:`Growth. In the Sacral Center. This gate brings a cycle to genuine completion — finishing what was started, letting a process run its natural course all the way to real increase, rather than cutting it short. Its impatience shows up at the end rather than the start: ending things — jobs, projects, relationships — right before the payoff that a little more follow-through would have delivered.`,
  43:`Insight. In the Ajna Center. This gate produces a sudden, individual "knowing" that arrives complete, without a step-by-step explanation attached to it — which makes it hard to justify to other people in the moment, even when it turns out to be right. The insight itself tends to be real; translating it into language other people can actually follow is the separate, harder part, since "I just know" doesn't function as proof to anyone standing outside it.`,
  44:`Alertness. In the Spleen Center. This gate carries an instinctive, fast read on people — recognizing almost instantly whether someone or something matches a pattern worth trusting or avoiding, based on accumulated past experience. That instinct is usually accurate, and it isn't infallible: it can also misfire against someone who genuinely doesn't fit the old pattern it's matching against.`,
  45:`The Gatherer. In the Throat Center. This gate gathers people and resources under one banner and has a natural instinct for distributing what's been gathered back to the group it leads — a material, practical kind of leadership, often tied to teaching or resource-sharing. The same gathering instinct, turned toward keeping what's gathered for personal benefit instead, reads as hoarding rather than leadership, even though the underlying pull to accumulate is identical.`,
  46:`Determination. In the G Center. This gate loves being embodied — genuinely enjoying physical presence, timing, and simply being in the right place at the right moment, almost by instinct. Its determination shows up as showing up: consistently being physically present for what matters, rather than forcing an outcome into being through sheer will.`,
  47:`Realization. In the Ajna Center. This gate processes past experiences — including confusing or difficult ones — until they suddenly resolve into real understanding, sometimes long after the experience itself happened. The confusion in the meantime isn't a malfunction; it's this gate's actual working process, sorting through the data before the realization is ready to arrive.`,
  48:`Depth. In the Spleen Center. This gate holds a real well of knowledge and talent, deep rather than broad, built through sustained practice over time. It comes paired with a fear of not being adequate to a given moment — a worry that the depth isn't enough right when it's needed — even in cases where the depth turns out to be more solid than the fear gave it credit for.`,
  49:`Principles. In the Solar Plexus Center. This gate holds real, felt principles about what is and isn't acceptable — in relationships, agreements, or a community — strong enough to justify walking away when those principles are violated. That conviction is genuine integrity when the principle itself is sound, and the same firmness can also enforce a standard that was never actually fair to begin with, without pausing to check which one it is.`,
  50:`Values. In the Spleen Center. This gate is a custodian of shared values and standards — upholding the agreed rules that let a group or family function, and reacting strongly when those standards get violated. That instinct is genuinely stabilizing for a group, and the same instinct can also defend an inherited rule purely out of habit, whether or not it still actually serves the people it was meant to protect.`,
  51:`Shock. In the Heart/Ego Center. This gate is jolted alive by sudden shock or competition — a jarring event that this gate periodically needs to feel fully awake and engaged, rather than something to avoid entirely. It thrives on being first, on the adrenaline of the unexpected, and without any real challenge for a long stretch it tends to go quietly stagnant, restless for the very jolt it insists it doesn't want.`,
  52:`Stillness. In the Root Center. This gate needs real, focused stillness — sitting with concentrated attention on one thing — before the right action actually becomes clear. That stillness isn't passivity; it's the concentration phase that makes the eventual action sharp and well-aimed, and skipped in favor of moving straight to action, the same energy tends to produce busy motion without much precision behind it.`,
  53:`Beginnings. In the Root Center. This gate has real energy for starting things — new projects, new phases — and a much weaker natural pull toward finishing them, which isn't a character flaw so much as where this gate's actual strength sits. Its follow-through tends to depend on something or someone else carrying a project past the point this gate's own energy naturally starts to fade.`,
  54:`Ambition. In the Root Center. This gate has real drive to rise — to improve status, circumstances, and material position, often starting from very little. That ambition functions as a genuine engine when it's aimed at building something concrete, and the same drive can also become an end in itself, disconnected from whatever the improved position was originally meant to be used for.`,
  55:`Spirit. In the Solar Plexus Center. This gate has access to real emotional abundance — including big, unpredictable mood swings that aren't a sign anything's wrong, just this gate's actual emotional range in motion. The lows here can feel disproportionately heavy relative to actual circumstances, and the highs disproportionately light, both part of the same wave rather than a verdict on how things really are.`,
  56:`Stimulation. In the Throat Center. This gate is a natural storyteller, gathering experiences to share as narrative — a genuine gift for making an experience come alive for someone who wasn't there for it. It runs on new material, though, which can also mean restlessness with the stories already told, and a pull toward bigger or newer experience just to stay interesting to itself.`,
  57:`Intuition. In the Spleen Center. This gate has fast, quiet, accurate intuition about right now — often received first through sound or a gut-level read rather than reasoning it out. It only speaks to the present moment, not to forecasting or planning ahead, and it's quiet enough to be missed or talked over by louder, more "logical"-sounding thoughts in the same moment.`,
  58:`Vitality. In the Root Center. This gate has real stamina and genuine joy specifically in fixing and improving things — a correcting energy that, aimed at something worth improving, produces real satisfaction and momentum. Aimed at something that's actually fine as it is, the same energy can turn into needless nitpicking, the drive to correct running ahead of anything that actually needs correcting.`,
  59:`Sexuality. In the Sacral Center. This gate is about breaking down the barriers between people to create real intimacy and bonding — a drive toward closeness that, at its root, is about dissolving separateness rather than being only about sex specifically. Directed at someone genuinely chosen for real closeness, that drive builds something lasting; used to dissolve boundaries more indiscriminately, the same intimacy can fail to hold once the initial closeness wears off.`,
  60:`Acceptance. In the Root Center. This gate works within real limitation — actual constraints of time, money, or circumstance — and finds a genuinely new way forward inside those limits rather than waiting for the limits to disappear first, which is real innovation, not resignation. The same gate can also mistake a limitation for permanent and unchangeable when it was actually possible to work around or past.`,
  61:`Inner Truth. In the Head Center. This gate carries a deep, private sense of knowing — a truth felt with real certainty even when it can't yet be explained or proven to anyone else. The mental pressure here is the need to eventually understand and articulate that inner knowing, and words forced onto it before it's actually ready tend to come out muddled rather than clear.`,
  62:`Details. In the Throat Center. This gate expresses in precise, concrete, factual terms — the specific detail rather than the big-picture feeling, which makes what it says easy to verify and hard to misread. That same focus on getting the small details right can also bury the larger point of what's being said underneath them.`,
  63:`Doubt. In the Head Center. This gate questions things that already appear settled or completed — not out of negativity, but because verifying what's already been decided is the actual mental pressure this gate is built to carry. That doubt is often what catches a real flaw others missed, and left unchecked against actual evidence, the same doubt can also spiral into questioning things that were genuinely fine.`,
  64:`Confusion. In the Head Center. This gate holds a flood of past impressions and images without yet having the context to make sense of them — mental pressure that feels like confusion because it genuinely is confusion, until enough new experience gives the old impressions a frame to click into. That confusion is the actual raw material for real understanding later, arriving well before the understanding itself does.`
};

// The 36 real Human Design channels -- each is the two gate-numbers that
// pair to form one complete, defined circuit. Structural data (which
// numbers pair up), not interpretive content -- same list as index.html's
// CHANNELS array, used here so the report prompt can tell the model which
// of a person's defined gates form an actual complete channel (the real,
// coherent, most load-bearing HD unit) versus an individual "hanging"
// gate with no partner defined.
export const CHANNELS = [
  [64,47],[61,24],[63,4],[17,62],[43,23],[11,56],[16,48],[20,57],[20,34],[32,54],
  [28,38],[18,58],[20,10],[31,7],[8,1],[33,13],[10,34],[15,5],[2,14],[46,29],
  [10,57],[57,34],[50,27],[45,21],[59,6],[42,53],[3,60],[9,52],[26,44],[25,51],
  [40,37],[35,36],[12,22],[49,19],[55,39],[30,41]
];
